//To print My Bio-data
#include<stdio.h>
#include<conio.h>
void main()
{
clrscr();
printf("Hi!this is Priyanka Biswas.\n My hobby is working with computer and listening music.\n Sanchari Basu is my fab fren as she is a broad-hearted girl.");
printf("I bliv dat we should do what our brain tells us not what our heart says as may heart can bring u luv,but it can't bring success 4 u.");
printf("Do u know what is my fab food?Its phuchka as it's sour as well as 2 chill.My fab flower is Yellow Dalia & yellow is my fab col 2.");
getch();
}

