#include<iostream.h>
#include<conio.h>
#include<string.h>
#include<stdio.h>
void main()
{
	clrscr();
	char a[100];
	int i;

cout<<"enter the string";

gets(a);
for( i=1;a[i];i++)
{
if(a.char At(i-1)==32)
{
if(s.char At(i)>90)
system.out.print(char)(s.char At(i)-32));
else
system.out.print((char)(s.char At(i)+32));
}
else
{
if(s.char At(i)==32)
system.out.print((char)(32));
else
system.out.print((char)(s.char At(i)+6));
}
}
}
}